### ISSUE TITLE
Replace login's background image 

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#11]

**Comment by ahmadzakiakmal** [comment]
The background in login page has been changed with the following image.

![raw image](https://e-rispkp.vercel.app/Landing.jpg)

Here's the preview of the new login page.

![preview of the image in the website](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/269328df-3a50-4910-a83f-490ab423c33d)
