### ISSUE TITLE
Peta pos to include more information in the label

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#12]
`Wilayah Manajemen Kebakaran -> Peta pos` to include some additional information as follows:
	- titik pos with some google streetview picture about the Pos.
	- Kemantren
	- Facilities.

The information is available in `Data Pos.xlsx`.

**Comment by ahmadzakiakmal** [comment]
Additional information has been added to each Post.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/227ef511-ca19-4a2c-b35c-8eb9d5f662ab)
