### ISSUE TITLE
New menu for listing public information

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#14]
Adding a new page to list all damkarmat's public information, as per what DTAP team has provided (pdf files).

Three main pdf's to be shown as icon-caption, while the rest is presented as regular lists.

Also, reordering the menu, as follows:
1. Wilayah Manajemen Kebakaran
2. Informasi dan Publikasi
	- group menu (header) dan link: Lihat informasi
2. Statistik Kejadian
3. Analisis Risiko

**Comment by ahmadzakiakmal** [comment]
The Information and Publication page has been created. Here's the preview.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/42d33e6d-486c-45f7-83ce-7d8d275e5d5a)

However, a bug was found that some links have the wrong path their respective file.
