### ISSUE TITLE
Location-based map

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#15]
In addition to issue #12 , e-RISPKP should get user's geolocation, and show relevant Pos WMK (calculated as the closest distance).

**Comment by ahmadzakiakmal** [comment]
The feature is now available and the closest post to the user is now displayed beneath the panic button. However, the accuracy of the algorithms may still need some validation.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/e81daf8a-d588-4cfa-92db-ed6f20c3779c)

**Comment by gtrdp** [comment]
The top left corner "pos terdekat" seems to work just fine.

Closing the issue for now.
