### ISSUE TITLE
New Map: "Sebaran Hidran Basah"

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#20]
A new map under `Wilayah Manajemen Kebakaran`: `Sebaran Hidran Basah`, as per the following GeoJSON: [Sebaran Hidran Basah.json](https://github.com/ahmadzaki2975/Prototype-RISPKP/files/14035430/Sebaran.Hidran.Basah.json).

Map preview:
![Sebaran Hidran Basah](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/4078156/1953d5d1-58f9-4c61-adf8-07ce5ecebe39)

**Comment by ahmadzakiakmal** [comment]
The new 'Sebaran Hidran' Map has been added. Let me know if there's a mistake.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/bff43995-68b1-47e9-a2d2-1ff6bb77d8a5)

**Comment by gtrdp** [comment]
LGTM!
