### ISSUE TITLE
New Map: "Sebaran SPBU Mini"

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#22]
A new map under `Wilayah Manajemen Kebakaran`: `Sebaran SPBU Mini`, as per the following GeoJSON: [Sebaran SPBU Mini.json](https://github.com/ahmadzaki2975/Prototype-RISPKP/files/14037029/Sebaran.SPBU.Mini.json).

Map preview:
![Sebaran SPBU Mini](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/4078156/1ca73444-b0ce-4d6b-a1cf-813b6d08a646)

**Comment by ahmadzakiakmal** [comment]
The new map has been added. Here's a preview of the map.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/9d390630-edf3-4ce2-8927-2c3446981fb9)

**Comment by gtrdp** [comment]
Nice one, thanks! But it seems like the header is still `Jangkauan Pos`, which should be something like `Peta Sebaran SPBU Mini`?

**Comment by ahmadzakiakmal** [comment]
Thank you for bringing this to my attention. I've addressed the issue with the header, and it now correctly displays as 'Titik Sebaran SPBU Mini.'

**Comment by gtrdp** [comment]
Thanks! Closing the issue.
