### ISSUE TITLE
New Map: "Sebaran SPBU"

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#23]
A new map under `Wilayah Manajemen Kebakaran`: `Sebaran SPBU`, as per the following GeoJSON: [Sebaran SPBU.json](https://github.com/ahmadzaki2975/Prototype-RISPKP/files/14037058/Sebaran.SPBU.json)

Map preview:
![Sebaran SPBU](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/4078156/81c87a4b-d968-4025-9c55-b453862d7ee1)

**Comment by ahmadzakiakmal** [comment]
The new `Sebaran SPBU` Map has been added. Let me know if there's a mistake.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/eb342ede-f6ac-4143-89ad-2483579ccc1f)

**Comment by gtrdp** [comment]
LGTM! Closing the issue.
