### ISSUE TITLE
Map size to match user's browser size

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#3]
The current map would go beyond the user's screen, at least on my laptop. Would be great to have the map to match user's window size, so they do not have to adjust the map to see the whole picture.

Jogja peta is an example of how a map can match user's screen: https://peta.jogjakota.go.id/map

**Comment by ahmadzakiakmal** [comment]
This issue should be fixed by now. 
Added the following fixes:
- Maps will no longer cause page overflow.
- Created hook and component to enable dynamic zoom on each map.
- Made Layout more responsive

**Comment by gtrdp** [comment]
Looks great, thanks!

Next time, can we link the commits to the specific issue? So we can track which commits fix which issues.

This may be of interest: https://gitdailies.com/articles/link-github-commit-to-issue/
