### ISSUE TITLE
Peta Kepadatan Komersial to use heatmap instead

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#8]
As per the ppt slide, peta kepadatan komersial uses heatmap to visualize the data, see below:
![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/4078156/2916dfda-8d01-493a-a8d1-9bac747d88b7)

Seems like heatmaps are also possible with Leaflet, there is a plugin for that: https://github.com/Leaflet/Leaflet.heat

**Comment by ahmadzakiakmal** [comment]
Using the current GeoJSON data provided by the DTAP team, I can extract points only from the coordinates of the polygons. This means that the heatmap will have heat points only on the perimeters of the polygons, as shown below.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/42d3aff3-d48b-40ba-bfb5-c2fca7bd7c92)

The most feasible approach I have tried is to use the <GeoJSON /> component from Leaflet, similar to the other maps, and then apply a blur effect to the polygons using CSS.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/5a96ffe8-909b-4711-9871-5e55ff452217)

**Comment by gtrdp** [comment]
Thanks. The workaround appears like a heat-map anyway, which seems to be okay to me (unless the DTAP team says otherwise).

Marking this issue as resolved for now.
