### ISSUE TITLE
Peta Jangkauan Pos does not look like it is suppose to look

### ISSUE THREAD

**Issue by gtrdp** [ahmadzaki2975/Prototype-RISPKP#9]
As per the ppt slide, Peta Jangkauan Pos looks like below:
![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/4078156/96e205b7-2ffd-4d20-a1f3-b1a2c54c40a0)

Is it the `GeoJSON` data from DTAP team? Or this page is still underconstruction?

As a reference, this is how the peta jangkauan pos looks like when this issue is posted, see below:
<img width="378" alt="image" src="https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/4078156/465c562e-8a46-4f3a-ba97-a28671f5ef0b">

**Comment by ahmadzakiakmal** [comment]
The GeoJSON data provided by the DTAP team appears to be different from the one in the PowerPoint presentation. It is most likely being confused with the GeoJSON data of Peta Pembagian Pos.

![image](https://github.com/ahmadzaki2975/Prototype-RISPKP/assets/87590846/b02eeb9a-c770-4daf-84ad-fdf9d55a63e9)

**Comment by gtrdp** [comment]
Now I see what the issue really is, thanks.

Will ask them to provide the correct GeoJSON file.

**Comment by gtrdp** [comment]
It seems we can put this issue aside for now.

**Comment by gtrdp** [comment]
It seems we can put this issue aside for now.
